### PR TITLE
Intial commit for supporting Oracle queries

### PR DESCRIPTION
**Pull request by michaenh**
Will shortly change to use .NET based Oracle client

### CODE REVIEW

**Comment by riha** [comment]
How do we solve the `Oracle.ManagedDataAccess.Client` dependency? It's currently not part of the NuGet package. One currently gets an compilation error as it's missing.
I can think of three options:
1. Take a dependency on the .NET managed alternative instead. 
2. Ship the currently used Orcale dll as part of the NuGet package.
3. Use the [Oracle NuGet package](https://www.nuget.org/packages/Oracle.ManagedDataAccess/) for dependency instead of the physical file. This would cause NuGet to download the Oracle dll from, NuGet.org as one adds this package. 

The downside of the structure today is really that even if one just wants to use the package to connect to Sql or SharePoint one will get the Oracle dll dependency in the solution anyway. But that might not be a bit problem? Thoughts?

We also need to think about how this is added to BizTalk to support runtime. For other utilities we don't have a MSI (as it's just one dll). Here we now have two dlls. Should we offer an MSI for this to install into BizTalk?

**Comment by michaenh** [comment]
Microsoft's recommendation is that you find a third-party client instead of .NET framework version:
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/oracle-and-adonet
So I think nr.1 is not a good solution.

I agree the downside about the Oracle dll  dependency even maybe you don't need it, but I guess it should not be a problem. Are there any possibilities to flag somehow what you want from the package only? From a msi instrallation maybe?

Yes I think we should offer an MSI install into biztalk.

**Comment by robinhultman** [comment]
We have the same problem in LookupUtility with the dependency to Sharepoint. My original thought was to include it as a Nuget dependency and also add it to the build script to include it in the MSI. I can see that I did'nt implement this all the way and the nuspec would need to be updated with a dependency. Personally I am fine with all dependencies being included but I am open for the other suggestions as well :).

**Comment by iBizBuildAdmin** [comment]
Let's include it as a NuGet dependency then. @michaenh will fix this, remove the dlls not checked in and add a NuGet dependency.

**Comment by robinhultman** [comment]
Is Oracle.ManagedDataAccess.12.2.1100.nuspec file checked in by misstake. Can you see if you can delete it?

**Pull request merged**
